[package]
name = "uf_ulog"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = true


[dependencies]
uf_ulog_macro = { path = "../uf_ulog_macro", optional = true }

[features]
default = []
derive = ["dep:uf_ulog_macro"]
